### PR TITLE
Update entry for Dragora (distribution)

### PR DESCRIPTION
**Pull request by selkfoster**
Hello,

I'm the maintainer of Dragora.  I am sending an update for the Dragora entry at the "Projects using musl".

Thanks.

### CODE REVIEW

**Comment by somasis** [comment]
Thanks for the updates. I'm not sure if I'd include this much in terms of bullet points though as it might make the list look a little slanted in terms of preferences?

**Comment by selkfoster** [comment]
Hi Somasis :-)

What do you mean by "slanted in terms of preferences"?.

**Comment by somasis** [comment]
Well, my worry is that if most of the distributions are just bullet points, but Dragora in particular is really detailed, it could make it seem as the wiki is recommending one distribution over another? It might be unfounded though. If you don't think so though I'll probably just commit this as is, it might just be me.

**Comment by selkfoster** [comment]
I thought that was the goal, to describe the characteristics or certain features of each distribution, but I don't know if there is a defined criterion/criteria in the musl wiki for this.  I don't have any particular bad intentions, like trying to outdo other distributions, I just followed the current pattern.

**Comment by selkfoster** [comment]
Don't worry,  I will try to be more briefly.

**Comment by selkfoster** [comment]
Hello Somasis,

I've updated the entry for Dragora again, I hope this is okay...

Let me know.

**Comment by somasis** [comment]
Thank you, I've pushed it in 4df50fe.

**Pull request closed without merging**
